### ISSUE TITLE
Any solution?

### ISSUE THREAD

**Issue by dasbego** [tony19-sandbox/bit-issue#1]
I found your issue and I'm having the same problem. Did you manage to find any solution to this problem? 
I've also added the config in the bit.json file and only `bit status` command seems to work, it fails during the build.

Also I've imported the compiler locally (without the --compile flag) and forked it to make my own compiler for my own custom vue components (where I still need to support i18n...). I've added the same alias config for bit in the compiler and it doesn't work either.

**Comment by tony19** [comment]
No solution yet, but I'm curious enough to investigate a bit.

**Comment by tony19** [comment]
My changes [here:](https://github.com/tony19/envs/commit/46ae3c614f507f5de782ad439dee63af5d95c382) pulls in Vue CLI's webpack config, which includes the alias configs. This allows the majority of the config to be inherited from the existing Vue CLI project.

**Comment by tony19** [comment]
I've published my [Vue CLI project bundler](https://bit.dev/tony19/envs/bundlers/vue), which can be imported into your bit projects:

```bash
bit import tony19.envs/bundlers/vue -c
```
